server:
  port: 9195
  servlet.context-path: /demo
  undertow.max-http-post-size: 0
spring:
  application.name: demo
  threads.virtual.enabled: true
  profiles:
    active: dev
  main.allow-bean-definition-overriding: true
  jackson.default-property-inclusion: non_absent
  freemarker.check-template-location: false
  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB
  servlet.multipart.resolve-lazily: true
  jpa:
    database: default
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

grpc:
  server:
    port: 3001

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.FilterChainProxy: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE